### ISSUE TITLE
feat: Requests logger middleware

### ISSUE THREAD

**Issue by TheWisePigeon** [TheWisePigeon/visio#22]
This middleware should only log requests either coming from the Frontend or authenticated requests going to the API.

**Comment by rafiramadhana** [comment]
@TheWisePigeon may i know the existing condition? do we log anything?

**Comment by rafiramadhana** [comment]
would this be related to https://github.com/TheWisePigeon/visio/issues/9?

**Comment by TheWisePigeon** [comment]
Yes in a way

**Comment by TheWisePigeon** [comment]
What I originally planned to do is kind of like assign an id to each request and pass the id down to all the middlewares so when they log stuff they can add the request id for more context

**Comment by rafiramadhana** [comment]
i see, i think we can solve this by generating a request id and _pass it around_ inside a context

**Comment by rafiramadhana** [comment]
If you're agree, I will create a PR to demonstrate it. Later on, we can continue the discussion on that PR. Wdyt?

**Comment by TheWisePigeon** [comment]
It would be great :)
